// Russian → English character name mapping for Jikan API search
export const CHARACTER_NAME_MAP: Record<string, string> = {
  'Айсака Тайга': 'Taiga Aisaka',
  'Тайга Айсака': 'Taiga Aisaka',
  'Томоя Окадзаки': 'Tomoya Okazaki',
  'Косэй Арима': 'Kousei Arima',
  'Кагуя Синомия': 'Kaguya Shinomiya',
  'Тору Хонда': 'Tohru Honda',
  'Хори Кёко': 'Kyoko Hori',
  'Хатиман Хикигая': 'Hachiman Hikigaya',
  'Сакута Адзусагава': 'Sakuta Azusagawa',
  'Сорота Канда': 'Sorata Kanda',
  'Сёя Исида': 'Shoya Ishida',
  'Мицуха Миямидзу': 'Mitsuha Miyamizu',
  'Вайолет Эвергарден': 'Violet Evergarden',
  'Инуяся': 'Inuyasha',
  'Сон Ги-хун': 'Seong Gi-hun',
  'Одиннадцать': 'Eleven',
  'Рик Граймс': 'Rick Grimes',
  'Геральт': 'Geralt of Rivia',
  'Уэнсдей': 'Wednesday Addams',
  'Джоэл': 'Joel Miller',
  'Джон Сноу': 'Jon Snow',
  'Уолтер Уайт': 'Walter White',
  'Сол Гудман': 'Saul Goodman',
  'Грегори Хаус': 'Gregory House',
  'Шерлок Холмс': 'Sherlock Holmes',
  'Дин Винчестер': 'Dean Winchester',
  'Фокс Малдер': 'Fox Mulder',
  'Шелдон Купер': 'Sheldon Cooper',
  'Рейчел Грин': 'Rachel Green',
  'Майкл Скотт': 'Michael Scott',
  'Тед Мосби': 'Ted Mosby',
  'Рю': 'Rue Bennett',
  'Фрэнк Андервуд': 'Frank Underwood',
  'Пабло Эскобар': 'Pablo Escobar',
  'Тони Сопрано': 'Tony Soprano',
  'Дейл Купер': 'Dale Cooper',
  'Мандалорец': 'The Mandalorian',
  'Локи': 'Loki',
  'Декстер': 'Dexter Morgan',
  'Профессор': 'The Professor',
  'Савако Куронума': 'Sawako Kuronuma',
  'Махуру Сиина': 'Mahiru Shiina',
  'Марин Китагава': 'Marin Kitagawa',
  'Банри Тада': 'Banri Tada',
  'Котаро Адзуми': 'Kotaro Azumi',
  'Арата Кайдзаки': 'Arata Kaizaki',
  'Наса Юдзаки': 'Nasa Yuzaki',
  'Эрика Синохара': 'Erika Shinohara',
  'Мисаки Такамия': 'Misaki Takamiya',
  'Тайти Яэгаси': 'Taichi Yaegashi',
  'Андзу Хосино': 'Anzu Hoshino',
  'Такао Акидзуки': 'Takao Akizuki',
  'Такаки Тоно': 'Takaki Tohno',
  'Харуки Сига': 'Haruki Shiga',
  'Ходака Морисима': 'Hodaka Morishima',
  'Судзумэ Ивато': 'Suzume Iwato',
  'Хана': 'Hana',
  'Нахо Такамия': 'Naho Takamiya',
  'Футаба Ёсиока': 'Futaba Yoshioka',
  'Мэй Татибана': 'Mei Tachibana',
  'Сидзуку Мидзутани': 'Shizuku Mizutani',
  'Риса Кодзуми': 'Risa Koizumi',
  'Нана Комацу': 'Nana Komatsu',
  'Тихая Аясэ': 'Chihaya Ayase',
  'Каори Фудзимия': 'Kaori Fujimiya',
  'Харуки Китахара': 'Haruki Kitahara',
  'Нацуо Фудзии': 'Natsuo Fujii',
  'Муги Авая': 'Mugi Awaya',
  'Кэндзи Койсо': 'Kenji Koiso',
  'Рэн': 'Ren',
  'Макия': 'Maquia',
  'Дзюн Нарусэ': 'Jun Naruse',
  'Цунэо': 'Tsuneo',
  'Ю Който': 'Yuu Koito',
  'Юдзу Айхара': 'Yuzu Aihara',
  'Мафую Сато': 'Mafuyu Sato',
  'Мияно': 'Miyano',
  'Юри Кацуки': 'Yuri Katsuki',
  'Миё Саймори': 'Miyo Saimori',
  'Сираюки': 'Shirayuki',
  'Сэнко-сан': 'Senko San',
  'Мисаки Аюдзава': 'Misaki Ayuzawa',
  'Мэгуми Нода': 'Megumi Noda',
  'Тайки Иномата': 'Taiki Inomata',
  'Макото Конно': 'Makoto Konno',
  'Кэй Кусанаги': 'Kei Kusanagi',
  'Мориока Морико': 'Moriko Morioka',
  'Наруми Момосэ': 'Narumi Momose',
  'Цукими': 'Tsukimi',
  'Тисэ Хатори': 'Chise Hatori',
  'Рикка Таканаси': 'Rikka Takanashi',
  'Раку Итидзё': 'Raku Ichijo',
  'Футаро Уэсуги': 'Fuutarou Uesugi',
  'Масамунэ Макабэ': 'Masamune Makabe',
  'Рю Ямада': 'Ryu Yamada',
  'Кадзуя Киносита': 'Kazuya Kinoshita',
  'Сёко Коми': 'Shouko Komi',
  'Хикару Кусакабэ': 'Hikaru Kusakabe',
}
