// Russian → English character name mapping for Jikan API search
export const CHARACTER_NAME_MAP: Record<string, string> = {
  // Олдовые (из старых списков, могут ещё где-то использоваться)
  'Сон Ги-хун': 'Seong Gi-hun',
  'Одиннадцать': 'Eleven',
  'Рик Граймс': 'Rick Grimes',
  'Геральт': 'Geralt of Rivia',
  'Уэнсдей': 'Wednesday Addams',
  'Джоэл': 'Joel Miller',
  'Джон Сноу': 'Jon Snow',
  'Уолтер Уайт': 'Walter White',
  'Сол Гудман': 'Saul Goodman',
  'Грегори Хаус': 'Gregory House',
  'Шерлок Холмс': 'Sherlock Holmes',
  'Дин Винчестер': 'Dean Winchester',
  'Фокс Малдер': 'Fox Mulder',
  'Шелдон Купер': 'Sheldon Cooper',
  'Рейчел Грин': 'Rachel Green',
  'Майкл Скотт': 'Michael Scott',
  'Тед Мосби': 'Ted Mosby',
  'Рю': 'Rue Bennett',
  'Фрэнк Андервуд': 'Frank Underwood',
  'Пабло Эскобар': 'Pablo Escobar',
  'Тони Сопрано': 'Tony Soprano',
  'Дейл Купер': 'Dale Cooper',
  'Мандалорец': 'The Mandalorian',
  'Локи': 'Loki',
  'Декстер': 'Dexter Morgan',
  'Профессор': 'The Professor',

  // Аниме — новые популярные
  'Эрен Йегер': 'Eren Yeager',
  'Лайт Ягами': 'Light Yagami',
  'Эдвард Элрик': 'Edward Elric',
  'Ринтаро Окабэ': 'Rintarou Okabe',
  'Гон Фрикс': 'Gon Freecss',
  'Сайтама': 'Saitama',
  'Лелуш Ламперуж': 'Lelouch Lamperouge',
  'Тандзиро Камадо': 'Tanjiro Kamado',
  'Юдзи Итадори': 'Yuji Itadori',
  'Дэндзи': 'Denji',
  'Лойд Форджер': 'Loid Forger',
  'Сигэо Кагэяма': 'Shigeo Kageyama',
  'Ай Хосино': 'Ai Hoshino',
  'Хитори Гото': 'Hitori Gotou',
  'Фрирен': 'Frieren',
  'Маомао': 'Maomao',
  'Момо Аясэ': 'Momo Ayase',
  'Дэвид Мартинес': 'David Martinez',
  'Габимару': 'Gabimaru',
  'Ёити Исаги': 'Yoichi Isagi',
  'Сёё Хината': 'Shoyo Hinata',
  'Такэмити Ханагаки': 'Takemichi Hanagaki',
  'Боджи': 'Bojji',
  'Торфинн': 'Thorfinn',
  'Фуси': 'Fushi',

  // Аниме — романтика / повседневность
  'Кёко Хори': 'Kyoko Hori',
  'Хори Кёко': 'Kyoko Hori',
  'Кагуя Синомия': 'Kaguya Shinomiya',
  'Тору Хонда': 'Tohru Honda',
  'Сёко Коми': 'Shouko Komi',
  'Футаро Уэсуги': 'Fuutarou Uesugi',
  'Миё Саймори': 'Miyo Saimori',
  'Махуру Сиина': 'Mahiru Shiina',
  'Кётаро Итикава': 'Kyotaro Ichikawa',
  'Мицуми Ивакура': 'Mitsumi Iwakura',
  'Юки Итосэ': 'Yuki Itose',
  'Наса Юдзаки': 'Nasa Yuzaki',
  'Андзу Хосино': 'Anzu Hoshino',
  'Нахо Такамия': 'Naho Takamiya',
  'Косэй Арима': 'Kousei Arima',
  'Савако Куронума': 'Sawako Kuronuma',
  'Мисаки Аюдзава': 'Misaki Ayuzawa',
  'Рикка Таканаси': 'Rikka Takanashi',
  'Томоя Окадзаки': 'Tomoya Okazaki',
  'Раку Итидзё': 'Raku Ichijo',
  'Банри Тада': 'Banri Tada',
  'Сорота Канда': 'Sorata Kanda',
  'Футаба Ёсиока': 'Futaba Yoshioka',
  'Тайга Айсака': 'Taiga Aisaka',
  'Айсака Тайга': 'Taiga Aisaka',
  'Хатиман Хикигая': 'Hachiman Hikigaya',
  'Марин Китагава': 'Marin Kitagawa',
  'Сакута Адзусагава': 'Sakuta Azusagawa',
  'Вайолет Эвергарден': 'Violet Evergarden',
  'Мейко Хомма': 'Meiko Honma',
  'Харуки Сига': 'Haruki Shiga',
  'Айла': 'Isla',
  'Мицуха Миямидзу': 'Mitsuha Miyamizu',
  'Сёя Исида': 'Shoya Ishida',
  'Ходака Морисима': 'Hodaka Morishima',
  'Судзумэ Ивато': 'Suzume Iwato',

  // Аниме — романтика (дополнительные)
  'Саю Огивара': 'Sayu Ogiwara',
  'Акари Ватанабэ': 'Akari Watanabe',
  'Каору Тонно': 'Kaoru Touno',
  'Исаки Магари': 'Isaki Magari',
  'Какэру Кома': 'Kakeru Komura',
  'Скимири': 'Shikimori',
  'Хикари Сахаси': 'Hikari Sahashi',
  'Черри': 'Cherry',
  'Наоя Мукай': 'Naoya Mukai',
  'Наги Умино': 'Nagi Umino',
  'Мицуёси Тада': 'Mitsuyoshi Tada',
  'Дзюнта Сираиси': 'Junta Shiraishi',
  'Рэйна Ахарэн': 'Reina Aharen',
  'Аля': 'Alya',
  'Такэо Гоуда': 'Takeo Gouda',
}
