// Russian → English character name mapping for Jikan API search
export const CHARACTER_NAME_MAP: Record<string, string> = {
  'Айсака Тайга': 'Taiga Aisaka',
  'Тайга Айсака': 'Taiga Aisaka',
  'Томоя Окадзаки': 'Tomoya Okazaki',
  'Косэй Арима': 'Kousei Arima',
  'Кагуя Синомия': 'Kaguya Shinomiya',
  'Тору Хонда': 'Tohru Honda',
  'Хори Кёко': 'Kyoko Hori',
  'Хатиман Хикигая': 'Hachiman Hikigaya',
  'Сакута Адзусагава': 'Sakuta Azusagawa',
  'Сорота Канда': 'Sorata Kanda',
  'Сёя Исида': 'Shoya Ishida',
  'Мицуха Миямидзу': 'Mitsuha Miyamizu',
  'Вайолет Эвергарден': 'Violet Evergarden',
  'Инуяся': 'Inuyasha',
  'Сон Ги-хун': 'Seong Gi-hun',
  'Одиннадцать': 'Eleven',
  'Рик Граймс': 'Rick Grimes',
  'Геральт': 'Geralt of Rivia',
  'Уэнсдей': 'Wednesday Addams',
  'Джоэл': 'Joel Miller',
  'Джон Сноу': 'Jon Snow',
  'Уолтер Уайт': 'Walter White',
  'Сол Гудман': 'Saul Goodman',
  'Грегори Хаус': 'Gregory House',
  'Шерлок Холмс': 'Sherlock Holmes',
  'Дин Винчестер': 'Dean Winchester',
  'Фокс Малдер': 'Fox Mulder',
  'Шелдон Купер': 'Sheldon Cooper',
  'Рейчел Грин': 'Rachel Green',
  'Майкл Скотт': 'Michael Scott',
  'Тед Мосби': 'Ted Mosby',
  'Рю': 'Rue Bennett',
  'Фрэнк Андервуд': 'Frank Underwood',
  'Пабло Эскобар': 'Pablo Escobar',
  'Тони Сопрано': 'Tony Soprano',
  'Дейл Купер': 'Dale Cooper',
  'Мандалорец': 'The Mandalorian',
  'Локи': 'Loki',
  'Декстер': 'Dexter Morgan',
  'Профессор': 'The Professor',
}
